loglevel="INFO"
rundebugserver=false
# .co covers .com and .co.uk too, obviously
# specify in lower case
filteredtext=["http",".co",".org",".net","www.","[img]"]

[database]
username="pyx"
password="password"
dbname="pyx_metrics"
# only 5432, only plaintext
host="10.0.0.1"
